In [9]:
import pandas as pd
import glob
import numpy as np
import re
from tqdm.auto import tqdm
import pickle
from pandarallel import pandarallel
import re
import plotly.graph_objects as go

pandarallel.initialize()

INFO: Pandarallel will run on 4 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.

In [10]:
data_in_csv = "../data/csv/"
data_in_comp = "../data/comp/"

In [11]:
df = pd.read_parquet(data_in_comp + r"gw-block-pre-post.parquet.gzip")

In [14]:
df

,state,district,block,india,1994-post,1994-pre,1994-stations,1995-post,1995-pre,1995-stations,...,2018-post,2018-pre,2018-stations,2019-post,2019-pre,2019-stations,2020-post,2020-pre,2020-stations,total-stations
0,andaman & nicobar,north & middle andaman,baratang island,india,NaN,NaN,NaN,3.45,0.09,1.0,...,NaN,NaN,NaN,1.94,0.32,2.0,NaN,NaN,NaN,2.0
1,andaman & nicobar,north & middle andaman,middle andaman,india,NaN,NaN,NaN,2.61,1.02,26.0,...,NaN,NaN,NaN,2.38,0.79,26.0,NaN,NaN,NaN,30.0
2,andaman & nicobar,south andaman,havelock island,india,NaN,NaN,NaN,3.08,1.64,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
3,andaman & nicobar,south andaman,neil island,india,NaN,NaN,NaN,4.39,2.27,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
4,andaman & nicobar,south andaman,south andaman,india,NaN,NaN,NaN,2.56,1.18,50.0,...,NaN,NaN,NaN,2.16,0.86,45.0,NaN,NaN,NaN,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5364,west bengal,uttar dinajpur,islampur,india,4.53,2.86,2.0,NaN,NaN,NaN,...,2.93,1.96,1.0,2.41,1.82,1.0,NaN,NaN,NaN,3.0
5365,west bengal,uttar dinajpur,itahar,india,4.42,2.74,2.0,NaN,NaN,NaN,...,4.02,1.78,2.0,2.56,2.20,1.0,NaN,NaN,NaN,5.0
5366,west bengal,uttar dinajpur,kaliganj,india,4.32,2.69,3.0,NaN,NaN,NaN,...,3.60,2.07,2.0,5.11,3.22,2.0,NaN,NaN,NaN,4.0
5367,west bengal,uttar dinajpur,karandighi,india,5.77,4.80,2.0,NaN,NaN,NaN,...,3.79,2.19,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0
5368,west bengal,uttar dinajpur,raiganj,india,3.96,2.25,2.0,NaN,NaN,NaN,...,4.09,1.58,2.0,2.58,1.90,1.0,NaN,NaN,NaN,2.0

In [ ]:
1994:1995    17.24
1997:1998     4.41
1998:1999    -2.08
1999:2000     5.70
2000:2001   -10.68
2001:2002     9.20
2002:2003     2.14
2003:2004     0.42
2004:2005    -4.91
2005:2006     7.61
2008:2009    20.33
2009:2010    -6.30
2010:2011   -12.30
2013:2014   -16.60
2014:2015     1.29
2015:2016     7.43
2016:2017     0.83
2017:2018    -4.62
2018:2019    18.05